---
- hosts: servers
  gather_facts: yes
  vars:
    package_names:
      - curl
      - git
      - vim

  tasks:
    - name: "Check if listed package is installed on Debian family"
      command: dpkg-query -l "{{ item }}"
      loop: "{{ package_names }}"
      register: package_check_deb
      ignore_errors: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: "Check if listed package is installed on RedHat family"
      command: rpm -q "{{ item }}"
      loop: "{{ package_names }}"
      register: package_check_rpm
      ignore_errors: yes
      when: ansible_facts['os_family'] == "RedHat"
      
    - name: "Print installed packages (Debian)"
      debug:
        msg: "Package {{ item.item }} is installed."
      loop: "{{ package_check_deb.results }}"
      when:
        - package_check_deb is defined
        - package_check_deb.results is defined
        - item is mapping
        - 'rc' in item
        - item.rc == 0
        - ansible_facts['os_family'] == "Debian"

    - name: "Print installed packages (RedHat)"
      debug:
        msg: "Package {{ item.item }} is installed."
      loop: "{{ package_check_rpm.results }}"
      when:
        - package_check_rpm is defined
        - package_check_rpm.results is defined
        - item is mapping
        - 'rc' in item
        - item.rc == 0
        - ansible_facts['os_family'] == "RedHat"
