---
- name: Verifica presenza pacchetti senza installazione (Debian, RedHat, SUSE)
  hosts: all
  gather_facts: yes
  become: no

  vars:
    packages_to_check:
      - curl
      - git
      - vim

  tasks:
    - name: Controlla se i pacchetti sono installati (Debian/Ubuntu)
      ansible.builtin.shell: "dpkg -s {{ item }} | grep 'Status: install ok installed'"
      register: pkg_check_deb
      ignore_errors: yes
      loop: "{{ packages_to_check }}"
      when: ansible_os_family == "Debian"

    - name: Stampa risultato controllo pacchetti Debian
      ansible.builtin.debug:
        msg: "Pacchetto {{ item.item }} è installato."
      loop: "{{ pkg_check_deb.results }}"
      when:
        - pkg_check_deb is defined
        - pkg_check_deb.results is defined
        - item is mapping
        - "'rc' in item"
        - item.rc == 0

    - name: Controlla se i pacchetti sono installati (RedHat/CentOS)
      ansible.builtin.shell: "rpm -q {{ item }}"
      register: pkg_check_rpm
      ignore_errors: yes
      loop: "{{ packages_to_check }}"
      when: ansible_os_family == "RedHat"

    - name: Stampa risultato controllo pacchetti RedHat
      ansible.builtin.debug:
        msg: "Pacchetto {{ item.item }} è installato."
      loop: "{{ pkg_check_rpm.results }}"
      when:
        - pkg_check_rpm is defined
        - pkg_check_rpm.results is defined
        - item is mapping
        - "'rc' in item"
        - item.rc == 0

    - name: Controlla se i pacchetti sono installati (SUSE)
      ansible.builtin.shell: "zypper --non-interactive info {{ item }} | grep 'Installed: Yes'"
      register: pkg_check_suse
      ignore_errors: yes
      loop: "{{ packages_to_check }}"
      when: ansible_distribution in ["SUSE", "openSUSE", "SLES", "openSUSE Leap"]

    - name: Stampa risultato controllo pacchetti SUSE
      ansible.builtin.debug:
        msg: "Pacchetto {{ item.item }} è installato."
      loop: "{{ pkg_check_suse.results }}"
      when:
        - pkg_check_suse is defined
        - pkg_check_suse.results is defined
        - item is mapping
        - "'rc' in item"
        - item.rc == 0
